name: Test Python

on:
  schedule:
    - cron: '0 23 * * *'  # 毎日 23:00 UTC（日本時間 8:00）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Python
        run: |
          python -c "print('Hello from GitHub Actions')"
